name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checking out Repo
        uses: actions/checkout@v2

      - name: Use node.js
        uses: actions/setup-node@v3

      - name: Build
        run: npm run build --if-present

      - name: Run Tests
        run: npm test
